spring:
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      cluster: null
      timeout: 100ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 5

logging:
  level:
    com.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,metrics