spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/product_service
    username: product
    password: product123
  elasticsearch:
    uris: http://localhost:9200
  kafka:
    bootstrap-servers: localhost:9092

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: product-images

logging:
  level:
    com.product: DEBUG
